"""add slug to topics

Revision ID: 0729a9e1c7f0
Revises: c18f332e9dde
Create Date: 2026-07-07 17:51:32.857143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0729a9e1c7f0'
down_revision: Union[str, Sequence[str], None] = 'c18f332e9dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_paper_topic', 'paper_topics', ['paper_id', 'topic_id'])
    op.add_column('topics', sa.Column('slug', sa.String(length=100), nullable=True))
    op.execute("""
        UPDATE topics
        SET slug = CASE name
            WHEN 'Natural Language Processing' THEN 'nlp'
            WHEN 'Computer Vision' THEN 'computer-vision'
            WHEN 'Machine Learning' THEN 'machine-learning'
            WHEN 'Deep Learning' THEN 'deep-learning'
            WHEN 'Reinforcement Learning' THEN 'reinforcement-learning'
            ELSE lower(replace(name, ' ', '-'))
        END
    """)
    op.alter_column(
        'topics',
        'slug',
        nullable=False
    )
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_column('topics', 'slug')
    #op.drop_constraint('uq_paper_topic', 'paper_topics', type_='unique')
    # ### end Alembic commands ###
