"""add paper content metadata

Revision ID: 2fd53216c578
Revises: fb5b06442646
Create Date: 2026-07-09 14:58:00.430996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd53216c578'
down_revision: Union[str, Sequence[str], None] = 'fb5b06442646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_contents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('paper_contents', sa.Column('extraction_status', sa.String(), nullable=False))
   # op.create_unique_constraint('uq_paper_topic', 'paper_topics', ['paper_id', 'topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_constraint('uq_paper_topic', 'paper_topics', type_='unique')
    op.drop_column('paper_contents', 'extraction_status')
    op.drop_column('paper_contents', 'page_count')
    # ### end Alembic commands ###
