"""add unique constraint to paper chunks

Revision ID: 7633fd3117f6
Revises: eaa8529f7f47
Create Date: 2026-07-19 10:42:18.539393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7633fd3117f6'
down_revision: Union[str, Sequence[str], None] = 'eaa8529f7f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_paper_content_chunk_index', 'paper_chunks', ['paper_content_id', 'chunk_index'])
    #op.create_unique_constraint('uq_paper_topic', 'paper_topics', ['paper_id', 'topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_paper_topic', 'paper_topics', type_='unique')
    op.drop_constraint('uq_paper_content_chunk_index', 'paper_chunks', type_='unique')
    # ### end Alembic commands ###
