"""create paper chunks table

Revision ID: 89df0d4173fe
Revises: 57904b4316d1
Create Date: 2026-07-17 11:06:45.885992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89df0d4173fe'
down_revision: Union[str, Sequence[str], None] = '57904b4316d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_content_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_content_id'], ['paper_contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_chunks_paper_content_id'), 'paper_chunks', ['paper_content_id'], unique=False)
    #op.create_unique_constraint('uq_paper_topic', 'paper_topics', ['paper_id', 'topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_paper_topic', 'paper_topics', type_='unique')
    op.drop_index(op.f('ix_paper_chunks_paper_content_id'), table_name='paper_chunks')
    op.drop_table('paper_chunks')
    # ### end Alembic commands ###
