"""add embedding column to paper chunks

Revision ID: ced95796e05e
Revises: 7633fd3117f6
Create Date: 2026-07-21 19:18:35.166946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ced95796e05e'
down_revision: Union[str, Sequence[str], None] = '7633fd3117f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    #op.create_unique_constraint('uq_paper_topic', 'paper_topics', ['paper_id', 'topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_constraint('uq_paper_topic', 'paper_topics', type_='unique')
    op.drop_column('paper_chunks', 'embedding')
    # ### end Alembic commands ###
