"""add paper sections table

Revision ID: d5be0fa9ed79
Revises: 2fd53216c578
Create Date: 2026-07-09 15:17:09.714164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5be0fa9ed79'
down_revision: Union[str, Sequence[str], None] = '2fd53216c578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_content_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_content_id'], ['paper_contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_sections_id'), 'paper_sections', ['id'], unique=False)
    #op.create_unique_constraint('uq_paper_topic', 'paper_topics', ['paper_id', 'topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_paper_topic', 'paper_topics', type_='unique')
    op.drop_index(op.f('ix_paper_sections_id'), table_name='paper_sections')
    op.drop_table('paper_sections')
    # ### end Alembic commands ###
