"""add section to paper chunks

Revision ID: eaa8529f7f47
Revises: 89df0d4173fe
Create Date: 2026-07-18 10:08:58.763230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa8529f7f47'
down_revision: Union[str, Sequence[str], None] = '89df0d4173fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_chunks', sa.Column('section', sa.Text(), nullable=True))
    #op.create_unique_constraint('uq_paper_topic', 'paper_topics', ['paper_id', 'topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_paper_topic', 'paper_topics', type_='unique')
    op.drop_column('paper_chunks', 'section')
    # ### end Alembic commands ###
